version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - python docs/get_wheel_artifact.py KolinGuo/RealRobot --py cp310
      - pip install wheelhouse/real_robot*.whl

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
