name: build-and-publish

on:
  push:
    branches: [main, dev]
    tags: ['v*']

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Strip optional dependency
        if: startsWith(github.ref, 'refs/tags/v') # if a tag is pushed
        run: |
          sed -i '/^\s*"xarm"/ {N; N; d;}' setup.py
          sed -i '/^dirty_template/c\dirty_template = "{tag}"' pyproject.toml
      - name: Install pypa/build
        run: "python -m pip install build --user"
      - name: Build a binary wheel and a source tarball
        run: "python -m build"
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*

  trigger-build-doc:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ReadTheDocs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}

  nightly-release:
    if: startsWith(github.ref, 'refs/heads/') # if a commit is pushed
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # create nightly release
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release'
          prerelease: true
          body: 'RealRobot development nightly release. This release is mainly for
            internal testing. Stable releases are published to pypi https://pypi.org/p/real-robot/'
          files: |
            dist/*

  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/v') # if a tag is pushed
    needs: build
    runs-on: ubuntu-latest
    environment: pypi_publish
    permissions:
      id-token: write # mandatory for PyPI trusted publishing
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
